spring.application.name=framework
server.port=8000

# redis ??
spring.data.redis.timeout=200
spring.data.redis.port=6379
#spring.data.redis.database=0
spring.data.redis.lettuce.pool.max-wait=300

# spring security 配置
# spring.security.user.name=ruiyu
# spring.security.user.password=ruiyu123
