spring.application.name=framework
server.port=8000

# JWT 配置
jwt.secret-key=your-secret-key-here-change-in-production

# redis ??
spring.data.redis.timeout=200
spring.data.redis.port=6379
#spring.data.redis.database=0
spring.data.redis.lettuce.pool.max-wait=300

# spring security 默认配置，实现了 UserDetailsService 后以下配置不生效
#spring.security.user.name=ruiyu
#spring.security.user.password=ruiyu123

# OAuth2 配置
github.client.clientId=Ov23liXSQ6SjTaKw4Xpq
github.client.clientSecret=77d46dd39ee72356559ebf49a4e772d847bc2795
github.client.authorizeUrl=https://github.com/login/oauth/authorize
github.client.accessTokenUrl=https://github.com/login/oauth/access_token
github.client.redirectUrl=http://localhost:8000/oauth/redirect
github.client.userInfoUrl=https://api.github.com/user


# DataSource Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springboot_demo?characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=root

